# Sqlite 3 for development and test environments
default: &default
  adapter: sqlite3
  pool: 8
  timeout: 6000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test .sqlite3

# Postgres for production
production:
  adapter: postgresql
  pool: 8
  timeout: 6000
  database: db/production.sqlite3